package com.jeannimi.messenger.common.exception_handling;

public enum ChatError {
  GROUP_MUST_HAVE_MEMBERS,
  GROUP_MEMBER_LIMIT_EXCEEDED,
  CANNOT_CREATE_PRIVATE_WITH_YOURSELF,
  CANNOT_REMOVE_YOURSELF,

  PRIVATE_CHAT_MUST_HAVE_TWO_MEMBERS,
  PRIVATE_CHAT_MUST_HAVE_PRIVATE_KEY,

  USER_ALREADY_IN_CHAT,
  MEMBER_NOT_FOUND,
  MEMBER_NOT_IN_CHAT,

  NOT_CHAT_MEMBER,
  ONLY_ADMIN_ALLOWED,
  LAST_ADMIN_CANNOT_BE_REMOVED,
  ADMIN_CANNOT_LEAVE,

  PRIVATE_CHAT_OPERATION_NOT_ALLOWED,

  CHAT_NAME_EMPTY,
  CHAT_NAME_TOO_LONG,
  CHAT_NAME_TOO_SHORT
}
