package com.jeannimi.messenger.common.exception_handling;

public enum MessageError {
  CONTENT_TOO_LONG,
  CONTENT_BLANK,
  FILE_EMPTY,
  FILE_TOO_LARGE,
  FILE_STORAGE_FAILED,
  FILE_NAME_INVALID,
  FILE_NAME_TOO_LONG,
  FILE_STORAGE_NAME_INVALID,
  FILE_STORAGE_NAME_TOO_LONG,
  FILE_CONTENT_TYPE_INVALID,
  FILE_CONTENT_TYPE_TOO_LONG,
  FILE_STORAGE_PATH_INVALID,
  FILE_STORAGE_PATH_TOO_LONG
}
