package com.jeannimi.messenger.kafka.event;

public enum EventType {
  CHAT_CREATED,
  CHAT_DELETED,
  CHAT_RENAMED,
  CHAT_MEMBER_ADDED,
  CHAT_MEMBER_REMOVED,
  CHAT_MEMBER_LEFT,
  MESSAGE_SENT,
  MESSAGE_READ,
  MESSAGE_DELETED
}
